[tool.poetry]
name = "pyraingen"
version = "2.0.0"
description = "A package for stochastically generating daily and subdaily rainfall in Australia with ifd constraining."
authors = ["Caleb Dykman"]
license = "None"
readme = "README.md"
packages = [{ include = "pyraingen", from = "src" }]
exclude = ["**/__pycache__", "**/*.pyd"]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
numpy = ">=1.23"
matplotlib = ">=3.6"
numba = ">=0.56"
netCDF4 = ">=1.6"
scipy = ">=1.9"
joblib = ">=1.2"
pandas = ">=1.5"
xarray = ">=2022.12"

[tool.poetry.dev-dependencies]
pytest = ">=7.0"
myst-nb = {version = "0.17.1", python = "3.8.5"}
sphinx-autoapi = "2.0.0"
sphinx-rtd-theme = "1.1.1"
jupyter = "1.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
